// Central registry of optimized WebP art (generated by scripts/optimize-images.mjs).
// Vite resolves these imports to hashed URLs at build time.
import bg01 from './backgrounds/bg-01.webp';
import bg02 from './backgrounds/bg-02.webp';
import bg03 from './backgrounds/bg-03.webp';
import bg04 from './backgrounds/bg-04.webp';
import bg05 from './backgrounds/bg-05.webp';
import bg06 from './backgrounds/bg-06.webp';
import bg07 from './backgrounds/bg-07.webp';
import bg08 from './backgrounds/bg-08.webp';
import bg09 from './backgrounds/bg-09.webp';
import bg10 from './backgrounds/bg-10.webp';
import bg11 from './backgrounds/bg-11.webp';
import bg12 from './backgrounds/bg-12.webp';
import bg13 from './backgrounds/bg-13.webp';
import bg14 from './backgrounds/bg-14.webp';
import bg15 from './backgrounds/bg-15.webp';
import bg16 from './backgrounds/bg-16.webp';
import bg17 from './backgrounds/bg-17.webp';
import bg20 from './backgrounds/bg-20.webp';
import bg21 from './backgrounds/bg-21.webp';
import bg22 from './backgrounds/bg-22.webp';
import bg23 from './backgrounds/bg-23.webp';
import bg24 from './backgrounds/bg-24.webp';
import bg25 from './backgrounds/bg-25.webp';
import bg26 from './backgrounds/bg-26.webp';
import bg27 from './backgrounds/bg-27.webp';

import card1 from './cards/card-1.webp';
import card2 from './cards/card-2.webp';
import card3 from './cards/card-3.webp';
import card4 from './cards/card-4.webp';
import card5 from './cards/card-5.webp';
import card6 from './cards/card-6.webp';
import card7 from './cards/card-7.webp';
import card30 from './cards/card-30.webp';
import card31 from './cards/card-31.webp';
import card32 from './cards/card-32.webp';
import card33 from './cards/card-33.webp';

import wheelYule from './wheel/yule.webp';
import wheelImbolc from './wheel/imbolc.webp';
import wheelOstara from './wheel/ostara.webp';
import wheelBeltane from './wheel/beltane.webp';
import wheelLitha from './wheel/litha.webp';
import wheelLughnasadh from './wheel/lughnasadh.webp';
import wheelMabon from './wheel/mabon.webp';
import wheelSamhain from './wheel/samhain.webp';

export const backgrounds: string[] = [
  bg01, bg02, bg03, bg04, bg05, bg06, bg07, bg08, bg09,
  bg10, bg11, bg12, bg13, bg14, bg15, bg16, bg17,
  bg20, bg21, bg22, bg23, bg24, bg25, bg26, bg27,
];

/** Прямое соответствие card_id → URL изображения. */
export const cardArtById: Record<string, string> = {
  'card-1': card1,
  'card-2': card2,
  'card-3': card3,
  'card-4': card4,
  'card-5': card5,
  'card-6': card6,
  'card-7': card7,
  'card-30': card30,
  'card-31': card31,
  'card-32': card32,
  'card-33': card33,
};

// Массив сохраняем для обратной совместимости (bgFor в рецептах и т.д.)
const cardArt: string[] = [
  card1, card2, card3, card4, card5, card6, card7,
  card30, card31, card32, card33,
];

/** Логотип праздника колеса года по его id. */
export const sabbatLogos: Record<string, string> = {
  yule: wheelYule,
  imbolc: wheelImbolc,
  ostara: wheelOstara,
  beltane: wheelBeltane,
  litha: wheelLitha,
  lughnasadh: wheelLughnasadh,
  mabon: wheelMabon,
  samhain: wheelSamhain,
};

/** Явная карта маршрутов → фоновое изображение. */
const ROUTE_BG: Record<string, string> = {
  '/':             bg25,  // Главная
  '/journal':      bg14,  // Дневник
  '/wheel':        bg11,  // Колесо года
  '/card':         bg17,  // Карта дня
  '/archive':      bg10,  // Архив карт
  '/wishes':       bg12,  // Книга желаний
  '/recipes':      bg15,  // Рецепты
  '/treasures':    bg16,  // Сокровища леса
  '/reminders':    bg08,  // Напоминания
  '/more':         bg04,  // Дальше в лес
  '/settings':     bg01,  // Настройки
  '/memories':     bg27,  // Воспоминания
  '/bookshelf':    bg26,  // Ведьмина полочка
  '/aesthetic':    bg22,  // Эстетика
  '/ingredients':  bg25,  // Ингредиенты
  '/my-calendar':  bg24,  // Мой календарь
};

// Пул для всего остального (арты рецептов и прочие произвольные ключи)
const fallbackPool: string[] = [bg02, bg03, bg05, bg06, bg07, bg09, bg13, bg20, bg21, bg23];

/**
 * Возвращает фон для маршрута или произвольного ключа.
 * Дочерние страницы /wheel/* получают тот же фон что и /wheel.
 */
export function bgFor(key: string): string {
  if (ROUTE_BG[key]) return ROUTE_BG[key];
  if (key.startsWith('/wheel/')) return bg11;
  // Хэш по пулу остатков — для арта рецептов и т.п.
  let h = 0;
  for (let i = 0; i < key.length; i++) h = (h * 31 + key.charCodeAt(i)) >>> 0;
  return fallbackPool[h % fallbackPool.length];
}

/** @deprecated Используй cardArtById[card.card_id] */
export function cardArtFor(index: number): string {
  return cardArt[((index % cardArt.length) + cardArt.length) % cardArt.length];
}
